### ISSUE TITLE
Issue with prodigal-gv script 

### ISSUE THREAD

**Issue by negilbert** [BenMinch/PIGv#1]
Hello, thanks for this tool! I am running into an issue with the scripts/prodigal-gv file when it starts running prodigal. I get a Permission denied error. I checked the file and it looks potentially corrupt, but I'm not sure. Everything else seems to be working fine! 

here's where the error occurs:
Running Prodigal
Traceback (most recent call last):
  File "/PIGv/scripts/prodigal_launcher.py", line 20, in <module>
    subprocess.call(cmd2, stdout=open("prodigal.out", "w"), stderr=open("prodigal.err", "w"))
  File "/PIGV/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/miniconda3/envs/PIGV/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "miniconda3/envs/PIGV/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'scripts/prodigal-gv'

Thanks!

**Comment by BenMinch** [comment]
Try going into the scripts folder and do "chmod +rwx *" . This should give
executable permission to all files in the folder.

**Comment by negilbert** [comment]
OK, I did that and it ran up until Prodigal and gave a slightly different error: 

Running Prodigal
Traceback (most recent call last):
  File "/PIGv/scripts/prodigal_launcher.py", line 20, in <module>
    subprocess.call(cmd2, stdout=open("prodigal.out", "w"), stderr=open("prodigal.err", "w"))
  File "/PIGV/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/PIGV/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/PIGV/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'scripts/prodigal-gv'
Done

**Comment by BenMinch** [comment]
It does seem like a problem with getting prodigal-gv to work on your
machine. It could maybe be because it is a windows or Mac? I have a Linux
machine so it is untested on those other platforms. I am not much of a
computer programmer myself so the only thought I have is to possibly delete
and redownload the prodigal-gv script, or if you already have normal
prodigal installed, you can edit the main PiGv script to use that instead.

**Comment by negilbert** [comment]
Yes i am using a Mac. I got it working by editing the scripts/prodigal-gv and scripts/viralrecall.py , replacing the "scripts/prodigal-gv" command with just "prodigal" after installing the prodigal program (just "conda install prodigal") within the PIGv conda environment. Thanks for the help!
