### ISSUE TITLE
Screening bins erro

### ISSUE THREAD

**Issue by XiaomengWang0413** [BenMinch/PIGv#2]
Hello, thanks for this tool!I have encountered the following problems during operation. May I ask what causes them and how can I solve them?：
Screening bins
cp: cannot stat 'EQ-6-2000m-vDNA/04_Viral_recall/viral_recall_out/batch_summary.txt/*.summary.tsv': Not a directory
scripts/viralrecall_post_screen.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Virus'][i]= 'no'
scripts/viralrecall_post_screen.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sum_score'][i]= data2['score'].sum()
scripts/viralrecall_post_screen.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Contamination'][i]= len(data2[data2['score'] < 0])
scripts/viralrecall_post_screen.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_contigs'][i]= len(data2)
scripts/viralrecall_post_screen.py:30: SettingWithCopyWarning:
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sum_score'][i]= data2['score'].sum()
scripts/viralrecall_post_screen.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Contamination'][i]= len(data2[data2['score'] < 0])
scripts/viralrecall_post_screen.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_contigs'][i]= len(data2)
scripts/viralrecall_post_screen.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Percent_negative'][i]=data['Contamination'][i]/data['Total_contigs'][i]
scripts/viralrecall_post_screen.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['PolB'][i]= 'yes'
Traceback (most recent call last):
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'GVOGm0003'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/viralrecall_post_screen.py", line 39, in <module>
    if data['GVOGm0003'][i] > 0:
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'GVOGm0003'
mv: cannot stat 'viralrecall_batch_summary.tsv': No such file or directory
Traceback (most recent call last):
  File "PIGv.py", line 125, in <module>
    viral_screen=pd.read_csv(output+'/05_Viral_screening/viralrecall_batch_summary.tsv', sep='\t')
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]

File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'EQ-6-2000m-vDNA/05_Viral_screening/viralrecall_batch_summary.tsv'

**Comment by BenMinch** [comment]
This error occurs when none of the viral bins pass screening. There could still be partial bins if you see them in the ncldv_good_bins folder.

**Comment by XiaomengWang0413** [comment]
> This error occurs when none of the viral bins pass screening. There could still be partial bins if you see them in the ncldv_good_bins folder.
Thank you for your timely reply. There are 10 genomes larger than 20kbp in my ncldv_good_bins. Are these genomes unable to pass the Screening bins?
Best

**Comment by XiaomengWang0413** [comment]
Maybe the reasult have some erro:cp: cannot stat 'EQ-6-2000m-vDNA/04_Viral_recall/viral_recall_out/batch_summary.txt/*.summary.tsv': Not a directory

**Comment by BenMinch** [comment]
The screening looks not only for length, but also for key marker genes as well as a positive viralrecall score (hits to known giant virus protein families). A negative score or lack of enough marker genes will cause it to not pass screening.

**Comment by XiaomengWang0413** [comment]
> The screening looks not only for length, but also for key marker genes as well as a positive viralrecall score (hits to known giant virus protein families). A negative score or lack of enough marker genes will cause it to not pass screening.

OK， Thank you for your timely reply.
