### ISSUE TITLE
KeyError: 'MirusMCP'

### ISSUE THREAD

**Issue by XiaomengWang0413** [BenMinch/PIGv#3]
Traceback (most recent call last):
  File "PIGv.py", line 338, in <module>
    ncldv_out=ncldv_out[ncldv_out['MirusMCP']>=1]
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/xiaomeng/miniconda3/envs/PIGV/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'MirusMCP'
:Hello, thank you for writing such excellent software, but I have encountered the above problems when running, may I ask how to solve this?

**Comment by BenMinch** [comment]
This usually comes up when you have a bin that has another mirusvirus
marked gene but no MCP. It shouldn't affect other outputs as mirusviruses
are resolved at the end.
